name: NPM publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '9.7.0'

      - name: Install dependencies
        run: pnpm install

      - run: pnpm build
      - run: pnpm test

      - name: Prepare for Github Packages
        run: |
          mkdir -p ${{ github.workspace }}/temp
          cp ${{ github.workspace }}/package.json ${{ github.workspace }}/temp
          awk '{gsub(/"name": "/, "\"name\": \"@uxiew/"); print}' ${{ github.workspace }}/temp/package.json > ${{ github.workspace }}/temp/package.json.tmp && mv ${{ github.workspace }}/temp/package.json.tmp ${{ github.workspace }}/temp/package.json
          # sed -i '' 's/"name": "/&@uxiew\//g' ${{ github.workspace }}/temp/package.json

      - name: Publish to jsr.io
        run: pnpm dlx jsr publish --allow-dirty

      - uses: JS-DevTools/npm-publish@v3
        name: Publish to NPM
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: 'https://registry.npmjs.org/'

      - uses: JS-DevTools/npm-publish@v3
        name: Publish to Github Packages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ github.workspace }}/temp
          registry: 'https://npm.pkg.github.com'
