name: NPM publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: '8.9.2'

      - name: Install dependencies
        run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: npm publish
      - uses: JS-DevTools/npm-publish@v3
        name: publish NPM
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: 'https://registry.npmjs.org/'

      - uses: JS-DevTools/npm-publish@v3
        name: publish to GitHub
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: 'https://npm.pkg.github.com'
